name: file_name_checking

on:
  push:
  pull_request:

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  Author_Lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: File Name Validator
        uses: batista/lint-filenames@v1
        with:
          path: './my-folder'
          pattern: '^.+\\..+$'
      
