name: Merge on Checks Pass

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your.email@example.com"

      - name: Merge if checks pass
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          # Check if all checks are successful
          CHECKS_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/checks" | \
            jq -r '.check_runs[] | select(.conclusion != "success") | .name')

          if [ -z "$CHECKS_STATUS" ]; then
            echo "All checks passed. Merging the pull request."
            curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"
          else
            echo "Not all checks passed. Skipping the merge."
          fi
