name: Auto Comment on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check if all checks have passed
        id: checks
        run: |
          checks=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
                      | jq -r '.[].commit.checks_url')
          check_statuses=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                $checks \
                                | jq -r '.[].status')
          echo "Check statuses: $check_statuses"
          if [[ ! "$check_statuses" =~ "failure" ]]; then
            echo "All checks passed. Commenting on the PR."
            echo "::set-output name=approved::true"
          else
            echo "Some checks failed. Not commenting on the PR."
            echo "::set-output name=approved::false"
          fi

      - name: Comment on PR
        if: steps.checks.outputs.approved == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"body": "All checks passed. Ready for review and merge."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
