name: Merge on Checks Pass

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 30 seconds
        run: sleep 30

      - name: Check GitHub Checks status
        id: checks
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const checks = response.data.filter(review => review.state === 'APPROVED');

            return {
              checks: checks,
              isReadyToMerge: checks.length > 0
            };

      - name: Merge PR if checks pass
        if: ${{ steps.checks.outputs.isReadyToMerge }}
        run: |
          echo "All checks passed. Merging pull request..."
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b merge-branch ${{ github.event.before }}
          git merge --no-ff ${{ github.event.after }}
          git push origin merge-branch
          gh pr merge ${{ github.event.number }} --squash --auto
