name: Auto Merge on Checks Pass

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 30 seconds
        run: sleep 30s

      - name: Check if all GitHub checks have passed
        id: checks
        run: echo "Check if all checks have passed"

      - name: Merge if checks passed
        if: steps.checks.outcome == 'success'
        run: |
          # Replace the following command with your merge command
          echo "Merging the pull request"
